// LOCALHOST
### SignUp
POST http://localhost:8000/api/signup HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@email.com",
  "password": "John@123"
}

### SignIn
POST http://localhost:8000/api/signin HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@email.com",
  "password": "John@123"
}

### Log Out
GET http://localhost:8000/api/logout

### Single User
GET http://localhost:8000/api/user/6654ce22497649caed109b83222